name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_monterey:
    strategy:
      matrix:
        xcode:
          - '13.4.1'
          - '14.1'
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run build
        run: make build-library
      - name: Run benchmark
        run: make benchmark
  unit_test_monterey:
    strategy:
      matrix:
        xcode:
          - '13.4.1'
          - '14.1'
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: make test-library
      - name: Selext Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode-14.1.0.app
      - name: Run tests
        run: make test-example
