name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-13
          xcode: '15.0.1'
        - os: macos-13
          xcode: '14.3.1'
        - os: macos-12
          xcode: '14.3.1'
        - os: macos-12
          xcode: '13.4.1'
    uses: ./.github/workflows/base.yml
    with:
      os: ${{ matrix.os }}
      xcode: ${{ matrix.xcode }}