name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        xcode:
          - '12.5.1'
          - '13.0'
          - '13.2.1'
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run build
        run: swift build
  unit_test:
    strategy:
      matrix:
        xcode:
          - '12.5.1'
          - '13.0'
          - '13.2.1'          
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: swift test --enable-test-discovery --enable-code-coverage | xcpretty